### ISSUE TITLE
Create resource with path param capture

### ISSUE THREAD

**Issue by cdelmas** [viniciusgerevini/http-test-server#1]
It would be great if we could capture path params, with something like that:
```
let resource = server.create_resource("/my-resource/{id}");
resource.method(GET).body_with_params(| params | format!("res_id={}", params.get("id").unwrap()));
```

Nice test tool btw ;)

**Comment by viniciusgerevini** [comment]
Thanks @cdelmas :)

That's a good suggestion. The part about matching custom provided path params sounds like a very useful feature for tests with random generated fixtures.

It's not a trivial change though, given the way I'm matching the URIs at the moment, but I'll give it some though. I think it shouldn't be too hard and it's a really nice feature to have.

Thanks :)
