### ISSUE TITLE
Allow a resource to accept multiple verbs

### ISSUE THREAD

**Issue by cdelmas** [viniciusgerevini/http-test-server#3]
It could be helpful to allow a resource to accept more than one verb (or config in general), or allow more than one resource with the same uri (which is the map key currently).

**Comment by viniciusgerevini** [comment]
I believe you found a bug. You should be able to create multiple resources with same URI. I took a quick look and I can see the problem. It will be a simple fix. Thank you :+1:

**Comment by viniciusgerevini** [comment]
In addition to that, I could maybe add a way to set ANY as HTTP method, so we don't need to create two resources for different methods with same response.

**Comment by cdelmas** [comment]
Good point, but in that case be careful that ANY should be the last matching method: if POST and ANY are defined for a given resource, the most specific (POST here) should be used, ANY being the « otherwise » case.
Nice suggestion, thanks for you time :+1:

**Comment by viniciusgerevini** [comment]
Fix implemented on version v1.0.1. I'll keep it open for now as a reminder about the wildcard method ANY.
